<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;
use Spatie\Permission\PermissionRegistrar;

final class RolePermissionSeeder extends Seeder
{
    /**
     * @var array<string, list<string>>
     */
    private array $roles = [
        'Director' => [
            'access-control.users.manage',
            'access-control.roles.manage',
            'audit-trail.view',
            'branch-users.manage',
            'branches.view',
            'branches.view-all',
            'contracts.manage',
            'contracts.view',
            'currency-settings.manage',
            'customers.manage',
            'customers.view',
            'daily-site-reports.approve',
            'daily-site-reports.archive',
            'daily-site-reports.correct',
            'daily-site-reports.create',
            'daily-site-reports.manage-expected',
            'daily-site-reports.override-self-approval',
            'daily-site-reports.return',
            'daily-site-reports.review',
            'daily-site-reports.submit',
            'daily-site-reports.update',
            'daily-site-reports.view',
            'daily-site-reports.view-costs',
            'daily-site-reports.view-dashboard',
            'dashboards.projects.view',
            'documents.archive',
            'documents.download',
            'documents.expiry.view',
            'documents.link',
            'documents.manage-types',
            'documents.unlink',
            'documents.update',
            'documents.upload',
            'documents.version',
            'documents.view',
            'documents.view-confidential',
            'exchange-rates.approve',
            'exchange-rates.create',
            'exchange-rates.update',
            'exchange-rates.view',
            'equipment.categories.manage',
            'equipment.assignments.manage',
            'equipment.costs.view',
            'equipment.create',
            'equipment.locations.manage',
            'equipment.readings.approve-correction',
            'equipment.readings.correct',
            'equipment.readings.create',
            'equipment.readings.override-self-approval',
            'equipment.retire',
            'equipment.update',
            'equipment.view',
            'equipment.view-all',
            'foundation.countries.manage',
            'foundation.currencies.manage',
            'notifications.manage-preferences',
            'notifications.view',
            'operations-dashboard.export',
            'operations-dashboard.view',
            'operations.projects.manage',
            'operations.reports.approve',
            'project-activities.manage',
            'project-users.manage',
            'projects.archive',
            'projects.create',
            'projects.update',
            'projects.view',
            'projects.view-all',
            'resources.staff.manage',
            'reporting-calendars.manage',
            'reporting-calendars.view',
            'expected-daily-reports.excuse',
            'site-users.manage',
            'sites.archive',
            'sites.create',
            'sites.update',
            'sites.view',
            'sites.view-all',
            'tenants.update',
        ],
        'Administrator' => [
            'access-control.users.manage',
            'branch-users.manage',
            'branches.view',
            'contracts.manage',
            'contracts.view',
            'currency-settings.manage',
            'customers.manage',
            'customers.view',
            'daily-site-reports.archive',
            'daily-site-reports.correct',
            'daily-site-reports.create',
            'daily-site-reports.manage-expected',
            'daily-site-reports.return',
            'daily-site-reports.review',
            'daily-site-reports.submit',
            'daily-site-reports.update',
            'daily-site-reports.view',
            'daily-site-reports.view-dashboard',
            'dashboards.projects.view',
            'documents.archive',
            'documents.download',
            'documents.expiry.view',
            'documents.link',
            'documents.manage-types',
            'documents.unlink',
            'documents.update',
            'documents.upload',
            'documents.version',
            'documents.view',
            'exchange-rates.create',
            'exchange-rates.update',
            'exchange-rates.view',
            'equipment.categories.manage',
            'equipment.assignments.manage',
            'equipment.create',
            'equipment.locations.manage',
            'equipment.readings.approve-correction',
            'equipment.readings.correct',
            'equipment.readings.create',
            'equipment.update',
            'equipment.view',
            'foundation.countries.manage',
            'foundation.currencies.manage',
            'notifications.manage-preferences',
            'notifications.view',
            'operations-dashboard.export',
            'operations-dashboard.view',
            'project-activities.manage',
            'project-users.manage',
            'projects.archive',
            'projects.create',
            'projects.update',
            'projects.view',
            'resources.staff.manage',
            'reporting-calendars.manage',
            'reporting-calendars.view',
            'expected-daily-reports.excuse',
            'site-users.manage',
            'sites.archive',
            'sites.create',
            'sites.update',
            'sites.view',
        ],
        'Project Manager' => [
            'branches.view',
            'contracts.view',
            'customers.view',
            'daily-site-reports.approve',
            'daily-site-reports.archive',
            'daily-site-reports.correct',
            'daily-site-reports.create',
            'daily-site-reports.return',
            'daily-site-reports.review',
            'daily-site-reports.submit',
            'daily-site-reports.update',
            'daily-site-reports.view',
            'daily-site-reports.view-costs',
            'daily-site-reports.view-dashboard',
            'dashboards.projects.view',
            'documents.download',
            'documents.link',
            'documents.update',
            'documents.upload',
            'documents.version',
            'documents.view',
            'equipment.costs.view',
            'equipment.assignments.manage',
            'equipment.create',
            'equipment.readings.approve-correction',
            'equipment.readings.correct',
            'equipment.readings.create',
            'equipment.update',
            'equipment.view',
            'notifications.manage-preferences',
            'notifications.view',
            'operations-dashboard.export',
            'operations-dashboard.view',
            'operations.projects.manage',
            'operations.reports.approve',
            'projects.update',
            'projects.view',
            'reporting-calendars.view',
            'site-users.manage',
            'sites.create',
            'sites.update',
            'sites.view',
        ],
        'Accountant' => [
            'branches.view',
            'equipment.costs.view',
            'equipment.view',
            'exchange-rates.create',
            'exchange-rates.update',
            'exchange-rates.view',
            'finance.payments.manage',
            'finance.reports.view',
        ],
        'Store Keeper' => [
            'inventory.stock.manage',
            'procurement.requests.view',
        ],
        'Site Manager' => [
            'branches.view',
            'customers.view',
            'daily-site-reports.create',
            'daily-site-reports.submit',
            'daily-site-reports.update',
            'daily-site-reports.view',
            'documents.download',
            'documents.upload',
            'documents.view',
            'equipment.view',
            'equipment.readings.correct',
            'equipment.readings.create',
            'notifications.manage-preferences',
            'notifications.view',
            'projects.view',
            'reporting-calendars.view',
            'sites.view',
        ],
        'Auditor' => [
            'audit-trail.view',
            'branches.view',
            'contracts.view',
            'customers.view',
            'daily-site-reports.view',
            'daily-site-reports.view-dashboard',
            'dashboards.projects.view',
            'documents.download',
            'documents.expiry.view',
            'documents.view',
            'equipment.costs.view',
            'equipment.view',
            'notifications.manage-preferences',
            'notifications.view',
            'operations-dashboard.export',
            'operations-dashboard.view',
            'projects.view',
            'reporting-calendars.view',
            'sites.view',
        ],
        'Fleet Manager' => [
            'branches.view',
            'customers.view',
            'documents.download',
            'documents.link',
            'documents.update',
            'documents.upload',
            'documents.version',
            'documents.view',
            'equipment.categories.manage',
            'equipment.assignments.manage',
            'equipment.costs.view',
            'equipment.create',
            'equipment.locations.manage',
            'equipment.readings.approve-correction',
            'equipment.readings.correct',
            'equipment.readings.create',
            'equipment.retire',
            'equipment.update',
            'equipment.view',
            'equipment.view-all',
            'notifications.manage-preferences',
            'notifications.view',
            'projects.view',
            'sites.view',
        ],
    ];

    public function run(): void
    {
        resolve(PermissionRegistrar::class)->forgetCachedPermissions();

        foreach ($this->permissions() as $permission) {
            Permission::query()->firstOrCreate([
                'name' => $permission,
                'guard_name' => 'web',
            ]);
        }

        foreach ($this->roles as $roleName => $permissions) {
            $role = Role::query()->firstOrCreate([
                'name' => $roleName,
                'guard_name' => 'web',
            ]);

            $role->givePermissionTo($permissions);
        }

        resolve(PermissionRegistrar::class)->forgetCachedPermissions();
    }

    /**
     * @return list<string>
     */
    private function permissions(): array
    {
        return collect($this->roles)
            ->flatten()
            ->unique()
            ->sort()
            ->values()
            ->all();
    }
}
