<?php

declare(strict_types=1);

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

final class OperationalNotification extends Notification
{
    use Queueable;

    /** @param array<string, mixed> $payload */
    public function __construct(public readonly array $payload)
    {
        //
    }

    /** @return list<string> */
    public function via(object $notifiable): array
    {
        return ['database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $message = (new MailMessage)
            ->subject((string) $this->payload['title'])
            ->line((string) $this->payload['message']);

        $url = $this->payload['action_url'] ?? null;

        if (is_string($url) && $url !== '') {
            $message->action('Open in PointERP', url($url));
        }

        return $message->line('This notification was generated by PointERP.');
    }

    /** @return array<string, mixed> */
    public function toArray(object $notifiable): array
    {
        return $this->payload;
    }
}
