<?php

declare(strict_types=1);

namespace App\Http\Controllers\Operations;

use App\Models\User;
use App\Services\AuditLogger;
use App\Services\DsrExceptionReport;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;

final class DsrExceptionExportController
{
    public function __invoke(Request $request, DsrExceptionReport $report, AuditLogger $auditLogger): StreamedResponse
    {
        $user = $request->user();
        abort_unless($user instanceof User && $user->can('operations-dashboard.export'), 403);

        $filters = $request->only(['from', 'to', 'project_id', 'site_id', 'status']);
        $rows = $report->rows($user, $filters);
        $auditLogger->record('operations.exception_export.generated', $user, $user, properties: ['filters' => $filters, 'row_count' => $rows->count()]);

        return response()->streamDownload(function () use ($rows, $user): void {
            $stream = fopen('php://output', 'wb');

            if ($stream === false) {
                return;
            }

            fputcsv($stream, ['Project', 'Site', 'Report date', 'Deadline', 'Expected status', 'DSR', 'DSR status', 'Submitted at', 'Site manager', 'Notified at', 'Escalated at', 'Generated by'], escape: '');

            foreach ($rows as $row) {
                fputcsv($stream, [
                    $row['project_name'],
                    $row['site_name'],
                    $row['report_date'],
                    $row['deadline_at'],
                    $row['status'],
                    $row['report_reference'],
                    $row['report_status'],
                    $row['submitted_at'],
                    $row['site_manager'],
                    $row['notified_at'],
                    $row['escalated_at'],
                    $user->name,
                ], escape: '');
            }

            fclose($stream);
        }, 'dsr-exceptions-'.now()->format('Ymd-His').'.csv', ['Content-Type' => 'text/csv']);
    }
}
