<?php

declare(strict_types=1);

namespace App\Http\Controllers\Operations;

use App\Models\User;
use App\Services\AuditLogger;
use App\Services\EquipmentFuelReport;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;

final class EquipmentFuelExportController
{
    public function __invoke(Request $request, EquipmentFuelReport $report, AuditLogger $auditLogger): StreamedResponse
    {
        $user = $request->user();
        abort_unless($user instanceof User && $user->can('equipment.export'), 403);
        $filters = $request->validate([
            'from' => ['nullable', 'date'], 'to' => ['nullable', 'date', 'after_or_equal:from'],
            'branch_id' => ['nullable', 'uuid'], 'project_id' => ['nullable', 'uuid'],
            'site_id' => ['nullable', 'uuid'], 'equipment_id' => ['nullable', 'uuid'],
            'transaction_type' => ['nullable', 'string'], 'source_type' => ['nullable', 'string'],
            'exception_status' => ['nullable', 'string'], 'status' => ['nullable', 'string'],
            'search' => ['nullable', 'string', 'max:255'],
        ]);
        $rows = $report->rows($user, $filters);
        $canViewCosts = $user->can('equipment.costs.view');
        $auditLogger->record('equipment.fuel_export.generated', $user, $user, properties: [
            'filters' => $filters, 'row_count' => $rows->count(),
        ]);

        return response()->streamDownload(function () use ($canViewCosts, $rows, $user): void {
            $stream = fopen('php://output', 'wb');
            if ($stream === false) {
                return;
            }

            $headers = ['Date', 'Asset code', 'Asset', 'Branch', 'Project', 'Site', 'Transaction', 'Fuel', 'Quantity', 'Unit', 'Source', 'Reference', 'Meter', 'Status', 'Exception', 'Exception reason'];
            if ($canViewCosts) {
                $headers[] = 'Unit cost';
                $headers[] = 'Total cost';
                $headers[] = 'Currency';
            }

            $headers[] = 'Generated by';
            fputcsv($stream, $headers, escape: '');

            foreach ($rows as $row) {
                $values = [
                    $row['transacted_at'], $row['equipment_code'], $row['equipment_name'],
                    $row['branch_name'], $row['project_name'], $row['site_name'],
                    $row['transaction_type'], $row['fuel_type'], $row['quantity'], $row['unit'],
                    $row['source_name'], $row['voucher_reference'], $row['meter_reading'],
                    $row['status'], $row['exception_status'], $row['exception_reason'],
                ];
                if ($canViewCosts) {
                    $values[] = $row['unit_cost'];
                    $values[] = $row['total_cost'];
                    $values[] = $row['currency_code'];
                }

                $values[] = $user->name;
                fputcsv($stream, $values, escape: '');
            }

            fclose($stream);
        }, 'equipment-fuel-'.now()->format('Ymd-His').'.csv', ['Content-Type' => 'text/csv']);
    }
}
