<?php

declare(strict_types=1);

namespace App\Http\Controllers\Operations;

use App\Models\EquipmentMaintenanceWorkOrder;
use App\Models\User;
use App\Services\AuditLogger;
use App\Services\EquipmentMaintenanceReport;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Symfony\Component\HttpFoundation\StreamedResponse;

final class EquipmentMaintenanceExportController
{
    public function __invoke(Request $request, EquipmentMaintenanceReport $report, AuditLogger $auditLogger): StreamedResponse
    {
        $user = $request->user();
        abort_unless($user instanceof User && $user->can('equipment.export'), 403);
        $filters = $request->validate([
            'from' => ['nullable', 'date'], 'to' => ['nullable', 'date', 'after_or_equal:from'],
            'branch_id' => ['nullable', 'uuid'], 'project_id' => ['nullable', 'uuid'],
            'site_id' => ['nullable', 'uuid'], 'equipment_id' => ['nullable', 'uuid'],
            'due_status' => ['nullable', Rule::in(['current', 'due_soon', 'overdue'])],
            'status' => ['nullable', Rule::in(['planned', 'approved', 'in_progress', 'completed', 'cancelled'])],
            'priority' => ['nullable', Rule::in(EquipmentMaintenanceWorkOrder::PRIORITIES)],
            'search' => ['nullable', 'string', 'max:255'],
        ]);
        $portfolio = $report->portfolio($user, $filters);
        $auditLogger->record('equipment.maintenance_export.generated', $user, $user, properties: [
            'filters' => $filters,
            'schedule_count' => $portfolio['schedules']->count(),
            'work_order_count' => $portfolio['work_orders']->count(),
        ]);
        $canViewCosts = $user->can('equipment.costs.view');

        return response()->streamDownload(function () use ($portfolio, $canViewCosts, $user): void {
            $stream = fopen('php://output', 'wb');
            if ($stream === false) {
                return;
            }

            $headers = ['Record type', 'Asset code', 'Asset', 'Branch', 'Reference / schedule', 'State', 'Due date / reported at', 'Due reading', 'Priority', 'Provider', 'Downtime hours', 'Documents'];
            if ($canViewCosts) {
                $headers[] = 'Total cost';
                $headers[] = 'Currency';
            }

            $headers[] = 'Generated by';
            fputcsv($stream, $headers, escape: '');

            foreach ($portfolio['schedules'] as $row) {
                $values = ['Schedule', $row['equipment_code'], $row['equipment_name'], $row['branch_name'], $row['name'], $row['due_status'], $row['next_due_date'], $row['next_due_reading'], null, null, null, null];
                if ($canViewCosts) {
                    $values[] = null;
                    $values[] = null;
                }

                $values[] = $user->name;
                fputcsv($stream, $values, escape: '');
            }

            foreach ($portfolio['work_orders'] as $row) {
                $values = ['Work order', $row['equipment_code'], $row['equipment_name'], $row['branch_name'], $row['reference'], $row['status'], $row['reported_at'], null, $row['priority'], $row['provider_name'], $row['downtime_hours'], $row['document_count']];
                if ($canViewCosts) {
                    $values[] = $row['total_cost'];
                    $values[] = $row['currency_code'];
                }

                $values[] = $user->name;
                fputcsv($stream, $values, escape: '');
            }

            fclose($stream);
        }, 'equipment-maintenance-'.now()->format('Ymd-His').'.csv', ['Content-Type' => 'text/csv']);
    }
}
