<?php

declare(strict_types=1);

use App\Enums\StaffDeploymentStatus;
use App\Models\AuditActivity;
use App\Models\Project;
use App\Models\Site;
use App\Models\Staff;
use App\Models\StaffDeployment;
use App\Models\User;
use App\Models\WorkforceTrade;
use App\Services\TenantContext;
use Database\Seeders\QuarryDemoSeeder;
use Database\Seeders\RolePermissionSeeder;
use Database\Seeders\WorkforceDemoSeeder;
use Inertia\Testing\AssertableInertia as Assert;

beforeEach(function (): void {
    $this->seed(RolePermissionSeeder::class);
    $this->seed(QuarryDemoSeeder::class);
    $this->seed(WorkforceDemoSeeder::class);

    resolve(TenantContext::class)->set(
        User::query()->where('email', 'lemi@gmail.com')->firstOrFail()->tenant,
    );
});

it('shows the workforce foundation to an authorised administrator', function (): void {
    $administrator = User::query()->where('email', 'lemi@gmail.com')->firstOrFail();

    $this->actingAs($administrator)
        ->get(route('workforce.index'))
        ->assertOk()
        ->assertInertia(fn (Assert $page): Assert => $page
            ->component('operations/workforce/index')
            ->has('trades', 8)
            ->has('deployments', 3)
            ->where('can.manageTrades', true)
            ->where('can.manageDeployments', true));
});

it('keeps workforce permissions unassigned from operational roles by default', function (): void {
    $siteEngineer = User::query()->where('email', 'luate@gmail.com')->firstOrFail();

    $this->actingAs($siteEngineer)
        ->get(route('workforce.index'))
        ->assertForbidden();
});

it('creates an audited tenant trade with an autogenerated code', function (): void {
    $administrator = User::query()->where('email', 'lemi@gmail.com')->firstOrFail();

    $this->actingAs($administrator)
        ->post(route('workforce.trades.store'), [
            'code' => '',
            'name' => 'Drill rig operator',
            'category' => 'skilled',
            'is_active' => true,
        ])
        ->assertRedirect(route('workforce.index', ['tab' => 'trades']));

    $trade = WorkforceTrade::query()->where('code', 'DRILL-RIG-OPERATOR')->firstOrFail();

    expect($trade->tenant_id)->toBe($administrator->tenant_id)
        ->and(AuditActivity::query()->where('event', 'workforce.trade.created')->where('subject_id', $trade->id)->exists())->toBeTrue();
});

it('ends the current deployment when staff is reassigned', function (): void {
    $administrator = User::query()->where('email', 'lemi@gmail.com')->firstOrFail();
    $staff = Staff::query()->where('email', 'luate@gmail.com')->firstOrFail();
    $project = Project::query()->where('reference', 'NAK-QRY')->firstOrFail();
    $site = Site::query()->where('project_id', $project->id)->where('reference', 'CRUSHER-YARD')->firstOrFail();
    $trade = WorkforceTrade::query()->where('code', 'SITE-ENGINEER')->firstOrFail();

    $this->actingAs($administrator)
        ->post(route('workforce.deployments.store'), [
            'staff_id' => $staff->id,
            'project_id' => $project->id,
            'site_id' => $site->id,
            'workforce_trade_id' => $trade->id,
            'starts_on' => now()->addDay()->toDateString(),
            'notes' => 'Temporary crusher-yard coverage.',
        ])
        ->assertRedirect(route('workforce.index'));

    expect(StaffDeployment::query()->where('staff_id', $staff->id)->where('status', StaffDeploymentStatus::Ended->value)->count())->toBe(1)
        ->and(StaffDeployment::query()->where('staff_id', $staff->id)->where('status', StaffDeploymentStatus::Active->value)->count())->toBe(1)
        ->and(StaffDeployment::query()->where('staff_id', $staff->id)->where('status', StaffDeploymentStatus::Active->value)->value('site_id'))->toBe($site->id);
});
